// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var TwitterDataProvider;
    TwitterDataProvider = (function() {

      function TwitterDataProvider() {}

      TwitterDataProvider.prototype.load = function(srcName, filter, callback) {
        switch (srcName) {
          case "Twit":
            return $.getJSON("https://api.twitter.com/1/statuses/user_timeline.json?screen_name=baio1980&count=100&include_rts=1&callback=?", function(data) {
              return callback((!data ? "error" : null), data);
            });
          default:
            return callback(null, []);
        }
      };

      TwitterDataProvider.prototype.save = function(srcName, item, callback) {
        return callback();
      };

      return TwitterDataProvider;

    })();
    return {
      twitterDataProvider: new TwitterDataProvider()
    };
  });

}).call(this);
