// Generated by CoffeeScript 1.3.3
(function() {
  var file, http, port, serv, util, webroot;

  serv = require("node-static");

  http = require("http");

  util = require("util");

  webroot = '.';

  port = 5000;

  file = new serv.Server(webroot, {
    cache: 600,
    headers: {
      'X-Powered-By': 'node-static'
    }
  });

  http.createServer(function(req, res) {
    return req.addListener('end', function() {
      if (req.url === "/") {
        req.url = "main.html";
      }
      return file.serve(req, res, function(err, result) {
        if (err) {
          console.error('Error serving %s - %s', req.url, err.message);
          res.writeHead(err.status, err.headers);
          return res.end();
          /*
                  if err.status == 404 or err.status == 500
                    file.serveFile util.format('/%d.html', err.status), err.status, {}, req, res
                  else
                    res.writeHead err.status, err.headers
                    res.end()
          */

        } else {
          return console.log('%s - %s', req.url, res.message);
        }
      });
    });
  }).listen(port);

  console.log('node-static running at http://localhost:%d', port);

}).call(this);
