// Generated by CoffeeScript 1.3.3
(function() {

  define(["Ural/Modules/DataProvider", "Modules/twitterDataProvider"], function(dataProvider, twitterDataProvider) {
    dataProvider.add("twi", twitterDataProvider.twitterDataProvider);
    return dataProvider.set("twi");
  });

}).call(this);
