// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["ural/Controllers/controllerBase"], function(controllerBase) {
    var TwitController;
    TwitController = (function(_super) {

      __extends(TwitController, _super);

      function TwitController() {
        return TwitController.__super__.constructor.apply(this, arguments);
      }

      return TwitController;

    })(controllerBase.ControllerBase);
    return {
      TwitController: TwitController
    };
  });

}).call(this);
